title = "Amirmasoud"
baseURL = "https://amirmasoud.me"
languageCode = 'en-us'
theme = 'ananke'
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
featured_image_class = "contain bg-top bg-black"
recent_posts_number = 10
recent_copy = " "

[params.ananke.social.share]
networks = [
  "email"
]

[params.ananke.social.follow]
new_window_icon = true
networks = [
  "linkedin",
  "github",
  "youtube"
]

[params.ananke.social.linkedin]
username = "amirmasoud-sheidayi"

[params.ananke.social.github]
username = "amirmasoud"

[params.ananke.social.youtube]
username = "Amirmasoud32"

[module]
  [[module.imports]]
    path = 'github.com/hugomods/images'
